<?php
/**
 * @file
 * Code for the bangpoundentity feature.
 */

/**
 * Implements hook_entity_info_alter().
 */
function bangpoundentity_entity_info_alter(&$info) {
  array_walk($info, function (&$info) {
    if (!isset($info['view_modes']['entity_label'])) {
      $info['view modes']['entity_label'] = array(
        'label' => t('Entity label'),
        'custom settings' => FALSE,
      );
    }
  });
}

/**
 * Implement hook_contextual_links_view_alter().
 */
function bangpoundentity_contextual_links_view_alter(&$element, &$items) {

  // Revise contextual link for display fields.
  if (isset($element['#element']['#view_mode']) && isset($element['#links']['field-ui-display'])) {
    $view_mode = $element['#element']['#view_mode'];
    $entity_info = entity_get_info($element['#element']['#entity_type']);
    if (isset($entity_info['view modes'][$view_mode])) {
      $settings = field_view_mode_settings($element['#element']['#entity_type'], $element['#element']['#bundle']);
      if (isset($settings[$view_mode]) && $settings[$view_mode]['custom_settings']) {
        $element['#links']['field-ui-display']['title'] =  t('Manage %view_mode display', array('%view_mode' => $entity_info['view modes'][$view_mode]['label']));
        $element['#links']['field-ui-display']['href'] .= '/'. $view_mode;
        $element['#links']['field-ui-display']['html'] = TRUE;
      }
    }
  }
}

/**
 * Implement hook_menu().
 */
function bangpoundentity_menu() {
  $items = array();
  $infos = entity_get_info();
  foreach ($infos['node']['view modes'] as $view_mode => $settings) {
    $items['node/%node/view/'. $view_mode] = array(
      'title' => $settings['label'],
      'type' => $view_mode == 'full' ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK,
      'page callback' => 'bangpoundentity_node_page_view',
      'page arguments' => array(1, 3),
      'file' => 'bangpoundentity.pages.inc',
      'access callback' => 'user_access',
      'access arguments' => array('administer content types'),
    );
  }
  return $items;
}

/**
 * Implement hook_menu_alter().
 */
function bangpoundentity_menu_alter(&$items) {
  if (module_exists('field_ui')) {
    foreach (entity_get_info() as $entity_type => $entity_info) {
      if ($entity_info['fieldable']) {
        foreach ($entity_info['bundles'] as $bundle_name => $bundle_info) {
          if (isset($bundle_info['admin'])) {
            // Extract path information from the bundle.
            $path = $bundle_info['admin']['path'];
            $items[$path .'/fields']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
            $items[$path .'/display']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
          }
        }
      }
    }
  }
}

/**
 * Implement hook_entity_view_alter().
 *
 * Contextual links are added after hook_node_view() in node_view(), so
 * use hook_entity_view_alter() to add the node's links.
 */
function bangpoundentity_entity_view_alter(&$build, $type) {
  if (user_access('access contextual links') && !empty($build['#entity_view_mode'])) {
    $entity_type = $build['#entity_view_mode']['entity_type'];
    $bundle = $build['#entity_view_mode']['bundle'];
    $id = $build['#entity_view_mode']['id'];

    // Avoid adding suggestions for lone bundles and default view modes.
    $info = entity_get_info($entity_type);
    $settings = field_view_mode_settings($entity_type, $bundle);

    if (isset($info['bundles'][$bundle]['admin']['bundle argument'])) {
      $path = implode('/', array_slice(explode('/', $info['bundles'][$bundle]['admin']['path']), 0, $info['bundles'][$bundle]['admin']['path'] - 1));
    }
    else {
      $path = $info['bundles'][$bundle]['admin']['path'];
    }
    if (!empty($id) && !empty($path)) {

      // Field UI doesn't provide its own contextual links, so we pretend to be
      // Field UI. This could backfire.

      if (isset($info['bundles'][$bundle]['admin']['bundle argument'])) {
        $build['#contextual_links']['field_ui'] = array($path, array($bundle));
      }
      else {
        $build['#contextual_links']['field_ui'] = array($path, array());
      }
    }
  }
}

/**
 * Implement hook_theme().
 */
function bangpoundentity_theme($existing, $type, $theme, $path) {
  return array(
    'node__entity_label' => array(
      'render element' => 'elements',
      'template' => 'node--entity-label',
      'base hook' => 'node',
    ),
  );
}

/**
 * Implement hook_preprocess_node().
 */
function bangpoundentity_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'entity_label') {
    $variables['theme_hook_suggestion'] = 'node__entity_label';

    // Add comment count to link title as in node_title_list().
    $node = $variables['node'];
    if (!empty($node->comment_count)) {
      $variables['title_attributes_array']['title'] = format_plural($node->comment_count, '1 comment', '@count comments');
    }
  }
}

/**
 * Implement hook_process_node().
 */
function bangpoundentity_process_node(&$variables) {
  if ($variables['view_mode'] == 'entity_label') {
    $variables['wrapper'] = !empty($variables['title_prefix']) | !empty($variables['title_suffix']);
  }
}
